# Generated by Django 3.2.9 on 2021-11-11 13:15

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', applications.account.models.UserManager()),
            ],
        ),
    ]
